// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaoD7yi1RIC39rI71Wz6WUn8Wft56EkR8',
    appId: '1:207217381099:android:7d28c3c0c86f403bc4f8ae',
    messagingSenderId: '207217381099',
    projectId: 'messenger-in-flutter',
    databaseURL: 'https://messenger-in-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'messenger-in-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClDqSpwpDV-8dAO8wvLWgMvCok1pIhTMU',
    appId: '1:207217381099:ios:0b6b6eac785f4559c4f8ae',
    messagingSenderId: '207217381099',
    projectId: 'messenger-in-flutter',
    databaseURL: 'https://messenger-in-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'messenger-in-flutter.appspot.com',
    androidClientId: '207217381099-8ru6pvf6ic80jkd0n8hf1thi22nqvbck.apps.googleusercontent.com',
    iosClientId: '207217381099-p3ctf95d2sh9qv3eko7rno0c707nn6tt.apps.googleusercontent.com',
    iosBundleId: 'com.skomarov.app',
  );
}
